name: BentoBot Auto Order Workflow

on:
#  schedule:
#    - cron: '0 23 * * *'      # JST 08:00 - メニューとカレンダー取得
#    - cron: '55 23 * * *'     # JST 08:55 - 自動注文
#    - cron: '10 0 * * *'      # JST 09:10 - 前日の注文Issueをクローズ
  workflow_dispatch:
    inputs:
      target:
        description: 'Which job to run?'
        required: true
        default: 'auto-order'
        type: choice
        options:
          - fetch-data
          - auto-order
          - close-issues

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.set.outputs.proceed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium python-dotenv
          sudo apt update
          sudo apt install -y wget unzip gnupg curl jq
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          CHROME_VER=$(google-chrome --version | grep -oP '[0-9.]+' | head -1)
          DRIVER_URL=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          wget -O chromedriver.zip "$DRIVER_URL"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

  fetch-data:
    runs-on: ubuntu-latest
    needs: setup
    if: github.event_name == 'schedule' && github.event.schedule == '0 23 * * *' || github.event.inputs.target == 'fetch-data'
    env:
      BENTO_EMAIL: ${{ secrets.BENTO_EMAIL }}
      BENTO_PASSWORD: ${{ secrets.BENTO_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Run menu and calendar fetchers
        run: |
          python fetch_calendar_status.py
          python menu_today.py

      - name: Commit updated JSON files
        run: |
          git config --global user.name github-actions
          git config --global user.email actions@github.com
          git add docs/menu_today.json docs/calendar_status.json
          git commit -m "🔄 Auto update menu & calendar JSON [skip ci]" || echo "No changes"
          git push

  auto-order:
    runs-on: ubuntu-latest
    needs: setup
    if: github.event_name == 'schedule' && github.event.schedule == '55 23 * * *' || github.event.inputs.target == 'auto-order'
    env:
      BENTO_EMAIL: ${{ secrets.BENTO_EMAIL }}
      BENTO_PASSWORD: ${{ secrets.BENTO_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  
      - name: Install dependencies
        run: |
          pip install selenium python-dotenv
  
      - name: Run automatic ordering
        run: |
          python process_orders.py

  close-issues:
    runs-on: ubuntu-latest
    needs: setup
    if: github.event_name == 'schedule' && github.event.schedule == '10 0 * * *' || github.event.inputs.target == 'close-issues'
    steps:
      - uses: actions/checkout@v4

      - name: Close old ordered issues
        run: |
          python close_old_issues.py
