name: Fetch Calendar Status

on:
  schedule:
    - cron: '0 23 * * *'  # JST 08:00 相当（UTC）
  workflow_dispatch:

jobs:
  fetch-calendar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium python-dotenv
          pip install selenium
          sudo apt update
          sudo apt install -y wget unzip gnupg curl jq
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          CHROME_VER=$(google-chrome --version | grep -oP '[0-9.]+' | head -1)
          DRIVER_URL=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          wget -O chromedriver.zip "$DRIVER_URL"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run calendar scraper
        run: python fetch_calendar_status.py

      - name: Commit calendar_status.json
        run: |
          git config --global user.name github-actions
          git config --global user.email actions@github.com
          git add docs/calendar_status.json
          git commit -m "🗓️ Auto-update calendar_status.json [skip ci]" || echo "No changes"
          git push
