name: Fetch Bento Menu

on:
  schedule:
    - cron: '0 0 * * 1-5'  # 平日JST 9:00（UTC 0:00）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-menu:
    runs-on: ubuntu-latest

    env:
      BENTO_EMAIL: ${{ secrets.BENTO_EMAIL }}
      BENTO_PASSWORD: ${{ secrets.BENTO_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium python-dotenv

      - name: Install Chrome & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl gnupg2
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9.]+' | head -1)
          CHROMEDRIVER_VERSION=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r --arg v "$CHROME_VERSION" '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          wget -O chromedriver.zip "$CHROMEDRIVER_VERSION"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Run fetch_menu.py
        # run: python fetch_menu.py
        run: python menu_today.py
        
      - name: Commit and push menu_today.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add menu_today.json
          git commit -m "🗓️ Auto-update menu_today.json [skip ci]" || echo "No changes"
          git push
